# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_drive.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10test_drive.proto\x12\x08\x63oolcars\"<\n\x03\x43\x61r\x12\x0c\n\x04make\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\x0b\n\x03VIN\x18\x04 \x01(\t\"\x19\n\nCarRequest\x12\x0b\n\x03VIN\x18\x01 \x01(\t2A\n\x0e\x43oolCarService\x12/\n\x06GetCar\x12\x14.coolcars.CarRequest\x1a\r.coolcars.Car\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_drive_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAR._serialized_start=30
  _CAR._serialized_end=90
  _CARREQUEST._serialized_start=92
  _CARREQUEST._serialized_end=117
  _COOLCARSERVICE._serialized_start=119
  _COOLCARSERVICE._serialized_end=184
# @@protoc_insertion_point(module_scope)
