# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fizzbuzz_pb2 as fizzbuzz__pb2


class ComputatorStub(object):
    """computes the fizzbuzz
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeFizzBuzz = channel.unary_unary(
                '/fizzbuzz.Computator/ComputeFizzBuzz',
                request_serializer=fizzbuzz__pb2.FizzBuzzDFRequest.SerializeToString,
                response_deserializer=fizzbuzz__pb2.FizzBuzzDFReply.FromString,
                )


class ComputatorServicer(object):
    """computes the fizzbuzz
    """

    def ComputeFizzBuzz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeFizzBuzz': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeFizzBuzz,
                    request_deserializer=fizzbuzz__pb2.FizzBuzzDFRequest.FromString,
                    response_serializer=fizzbuzz__pb2.FizzBuzzDFReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fizzbuzz.Computator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Computator(object):
    """computes the fizzbuzz
    """

    @staticmethod
    def ComputeFizzBuzz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fizzbuzz.Computator/ComputeFizzBuzz',
            fizzbuzz__pb2.FizzBuzzDFRequest.SerializeToString,
            fizzbuzz__pb2.FizzBuzzDFReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
