# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fizzbuzz.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66izzbuzz.proto\x12\x08\x66izzbuzz\"%\n\x11\x46izzBuzzDFRequest\x12\x10\n\x08\x63ol_name\x18\x01 \x01(\t\"\x1d\n\x0f\x46izzBuzzDFReply\x12\n\n\x02\x64\x66\x18\x01 \x01(\t2Y\n\nComputator\x12K\n\x0f\x43omputeFizzBuzz\x12\x1b.fizzbuzz.FizzBuzzDFRequest\x1a\x19.fizzbuzz.FizzBuzzDFReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fizzbuzz_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIZZBUZZDFREQUEST._serialized_start=28
  _FIZZBUZZDFREQUEST._serialized_end=65
  _FIZZBUZZDFREPLY._serialized_start=67
  _FIZZBUZZDFREPLY._serialized_end=96
  _COMPUTATOR._serialized_start=98
  _COMPUTATOR._serialized_end=187
# @@protoc_insertion_point(module_scope)
